#!/usr/bin/env python3
"""Turns PCem's own nvr/default/*.nvr into a C table the guest carries.

An AT-class machine with no CMOS contents stops at POST with
"161-System Options Not Set-(Run SETUP)" and waits for F1. PCem ships a clean
default for every machine that needs one and its own nvrfopen() falls back to
nvr/default/<name> - but the sandbox has no such folder and a project cannot
supply one, because the CMOS is not firmware and not a user file.

So the defaults travel INSIDE the core. They are PCem's own data under the
same GPL-2.0 as the rest of it (PLAN.md section 8), 21 KB for all 44 files,
and shipping them is what makes a machine start from a clean, identical CMOS
every time instead of from whatever the last person's BIOS setup left.

usage: gen-nvr-defaults.py <extern/pcem/nvr/default> <out.c>
"""

import os
import sys


def main():
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    src, out = sys.argv[1], sys.argv[2]
    names = sorted(n for n in os.listdir(src)
                   if os.path.isfile(os.path.join(src, n)))

    with open(out, "w") as f:
        f.write("/* GENERATED by tools/gen-nvr-defaults.py - do not edit.\n"
                " * PCem's nvr/default/, so a machine starts from a clean CMOS.\n"
                " * Source: extern/pcem/nvr/default (GPL-2.0, PCem's own data).\n"
                " */\n"
                "#include <stddef.h>\n"
                "#include <string.h>\n"
                "#include <stdint.h>\n\n")
        for i, n in enumerate(names):
            data = open(os.path.join(src, n), "rb").read()
            f.write("static const uint8_t nvr_%d[] = {" % i)
            f.write(",".join(str(b) for b in data))
            f.write("};\n")
        f.write("\nstatic const struct { const char *name; const uint8_t *data; "
                "int len; } nvr_defaults[] = {\n")
        for i, n in enumerate(names):
            size = os.path.getsize(os.path.join(src, n))
            f.write('        { "%s", nvr_%d, %d },\n' % (n, i, size))
        f.write("};\n\n"
                "int pcem_nvr_default(const char *name, const uint8_t **data, int *len)\n"
                "{\n"
                "        size_t i;\n"
                "        for (i = 0; i < sizeof nvr_defaults / sizeof *nvr_defaults; i++)\n"
                "                if (!strcmp(nvr_defaults[i].name, name)) {\n"
                "                        *data = nvr_defaults[i].data;\n"
                "                        *len = nvr_defaults[i].len;\n"
                "                        return 1;\n"
                "                }\n"
                "        return 0;\n"
                "}\n\n"
                "int pcem_nvr_default_count(void)\n"
                "{\n"
                "        return (int)(sizeof nvr_defaults / sizeof *nvr_defaults);\n"
                "}\n")
    print("%s: %d default NVRAMs" % (out, len(names)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
